//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобиль
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Автомобиль()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public System.Guid id { get; set; }
        public string Описание { get; set; }
        public bool Доступность { get; set; }
        public System.Guid idМодель { get; set; }
        public decimal Стоимость { get; set; }
        public System.Guid idВладелец { get; set; }
        public string Фото { get; set; }
    
        public virtual Модель Модель { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }

     
    }
}
