//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public System.Guid id { get; set; }
        public System.Guid idПользователь { get; set; }
        public System.Guid idАвтомобиль { get; set; }
        public System.DateTime ДатаВремяНачалаАредны { get; set; }
        public System.DateTime ДатаВремяКонцаАренды { get; set; }
    
        public virtual Автомобиль Автомобиль { get; set; }
        public virtual Пользователь Пользователь { get; set; }
    }
}
